language: scala
scala:
- 2.13.2
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  -x scripts/decrypt_keys.sh; fi
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 4.0.0
- gem install jemoji -v 0.11.1
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  ++$TRAVIS_SCALA_VERSION clean coverageOff compile publish; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publish_microsite.sh; fi
env:
  global:
  - secure: oJbSN+qjvqKW/vhjyTuumBxKKmBRVKIBSBQUPJ9wacUlNvQpH1vaAtdRvM6GkY/lXtg9fFmht9vYQGYZrleUU1YFx/EgqLTS8nTM6rlB3zPAocZLEByYEePwYWw6imRam+HuMuwFIEsGjBEaIdtMjiyaCblFjFA/gqBM76/0w/BHS9Whgen3eq49Infb9KPuXOcKp8Bpdef2ec+i51ayXq9j62NgrloEwMjVlvUu3tqSG6wWGkwTR8haPA5wnA4nohaguFHvze9g3Re0sQO7xspkRGvrGcM96WCx8m9lxsvOhRDXhoG/Nkhw6ckvNJTMDR/jSoNfS50TRHkhPanlmIpdjVdgMAouSlxiUCVN7+G6QHU9SDOF+Le1+73Ohtq093SpY3N3hZiKi+9M6OyETL/I1quCpQnhG1puL0mgcZWm9uV7AnPAqoYU7WBz77bm1hAXucfZq+COGIdo449gPHU5LAMvFVqd+zn3YruXp8nz8Dw6PYvQwbPb3mI1AxJ4211pbaXO0hsFbTwBu/B6SSclAbAnP3r6vyrHJ7e42W8CokhV5m+V/N6gzoHNXbcIqCP3ijE0N/eO1xu07QtPLfdSDaJBbTZl3q8vRu3QUkqApPB3/dN3vcg2MPrrEWdxxbdbUxLz/bFM/Mj40BKs0EiHaBjROsgLwOyqgl0Jbl0=
  - secure: l00cdQn4ERoPuB2L1dutbGWp02iXh7U+2H98eff5SLSOb1b7w/D+FeoZhzj/T+WNP+qm/n4lx1tW0AEbFK9yfAhbzDrhJomRrCW7E48DHh2648Po1EjSvDfqnL8BMAQB20v0JEJA14qHyuiHptG3b8gZj58OABC9VlQUidcaM9jrzW9meoslSybwZke/c0vtFbEHdbGy48iRaAcAPx/RtMR7LeB1co4L9Wn51KCWmfLKyr6j0pbVpcGtkKbQDV9T4jBs390WC3zfpNUa+zGwd5+z0IQl52w1aV06DFUyxkFSlf9+NuqMP1qMwhGk6nX5bVCgMhSMY8vAMe1wjzUfQaSgaLPMqqxThBFkkRC1hDPGqc87rTKgX+NAxNB9VVfit0yCN/3Hh4qY2QrTz2QbSFf2Nw+rMvxFp3WVgTDIDmVfk+lWMp7eRiwdvK/yuJ4H+b+zj4Mu4ZZFFqAkx4lhxrj+wcu4h05En6jTPBZdbpB7X/uOxwNAaCefb5+lk3zRR2LnnJtQSKsF1SuhC8M9iM9cOzMmAcYtBkb9nLJn0SOMfAyqDXtCU61JQRc1tWixZyXZC8Ye8gjndr4QpBYK8KETfdCj/pzWIxoAjxLo4Sq+GNcTxMmnqxPkvsM6RbYLXttzggRqTxG0DRRjZlGSpV6bMNgBJ8LNIIguTh2Q/Ys=
